// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAZ7W5bCEbKXZW9oDNYyNljhx1ADIIgHs',
    appId: '1:799549887454:web:036524bbaee32c84d4434f',
    messagingSenderId: '799549887454',
    projectId: 'grup-47',
    authDomain: 'grup-47.firebaseapp.com',
    storageBucket: 'grup-47.firebasestorage.app',
    measurementId: 'G-B0CN8BRGJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLEWy6C6Ebzilrl18bJTmmdeKMDcwMmUM',
    appId: '1:799549887454:android:49a7af9117b24b71d4434f',
    messagingSenderId: '799549887454',
    projectId: 'grup-47',
    storageBucket: 'grup-47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqJBp-i89ioPJZLCbVON6SUebnWD5fTTk',
    appId: '1:799549887454:ios:b24959d3838ca1ded4434f',
    messagingSenderId: '799549887454',
    projectId: 'grup-47',
    storageBucket: 'grup-47.firebasestorage.app',
    iosBundleId: 'com.example.slack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqJBp-i89ioPJZLCbVON6SUebnWD5fTTk',
    appId: '1:799549887454:ios:b24959d3838ca1ded4434f',
    messagingSenderId: '799549887454',
    projectId: 'grup-47',
    storageBucket: 'grup-47.firebasestorage.app',
    iosBundleId: 'com.example.slack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAZ7W5bCEbKXZW9oDNYyNljhx1ADIIgHs',
    appId: '1:799549887454:web:4c09605365919bb1d4434f',
    messagingSenderId: '799549887454',
    projectId: 'grup-47',
    authDomain: 'grup-47.firebaseapp.com',
    storageBucket: 'grup-47.firebasestorage.app',
    measurementId: 'G-X008YZ0YD9',
  );
}
